server {
    listen 80;
    listen [::]:80;

    server_name _;

    location ^~ /api/ {

        proxy_pass http://127.0.0.1:8080/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {

        root /opt/mytestapp/frontend;

        index index.html;

        try_files $uri $uri/ /index.html;
    }

    location = /nginx-health {
        return 200 "OK\n";
    }
}
